import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/one">One</Link>
        </li>
        <li>
          <Link to="/i01one">I01One</Link>
        </li>
        <li>
          <Link to="/i02">I02</Link>
        </li>
        <li>
          <Link to="/i10">I10</Link>
        </li>
        <li>
          <Link to="/i11">I11</Link>
        </li>
        <li>
          <Link to="/i12">I12</Link>
        </li>
        <li>
          <Link to="/i01">I01</Link>
        </li>
        <li>
          <Link to="/i021">I021</Link>
        </li>
        <li>
          <Link to="/i03">I03</Link>
        </li>
        <li>
          <Link to="/i04">I04</Link>
        </li>
        <li>
          <Link to="/i05">I05</Link>
        </li>
        <li>
          <Link to="/i01ue">I01UE</Link>
        </li>
        <li>
          <Link to="/i02ue">I02UE</Link>
        </li>
        <li>
          <Link to="/i011">I011</Link>
        </li>
        <li>
          <Link to="/1440">1440</Link>
        </li>
        <li>
          <Link to="/page">Page</Link>
        </li>
        <li>
          <Link to="/page1">Page1</Link>
        </li>
        <li>
          <Link to="/page2">Page2</Link>
        </li>
        <li>
          <Link to="/i13">I13</Link>
        </li>
        <li>
          <Link to="/page3">Page3</Link>
        </li>
        <li>
          <Link to="/i16">I16</Link>
        </li>
        <li>
          <Link to="/page4">Page4</Link>
        </li>
        <li>
          <Link to="/i031">I031</Link>
        </li>
        <li>
          <Link to="/page5">Page5</Link>
        </li>
        <li>
          <Link to="/page6">Page6</Link>
        </li>
        <li>
          <Link to="/i041">I041</Link>
        </li>
        <li>
          <Link to="/i06">I06</Link>
        </li>
        <li>
          <Link to="/i07">I07</Link>
        </li>
        <li>
          <Link to="/i08">I08</Link>
        </li>
        <li>
          <Link to="/i09">I09</Link>
        </li>
        <li>
          <Link to="/i101">I101</Link>
        </li>
        <li>
          <Link to="/page7">Page7</Link>
        </li>
        <li>
          <Link to="/one1">One1</Link>
        </li>
        <li>
          <Link to="/i051">I051</Link>
        </li>
        <li>
          <Link to="/page8">Page8</Link>
        </li>
        <li>
          <Link to="/page9">Page9</Link>
        </li>
        <li>
          <Link to="/i07r">I07r</Link>
        </li>
        <li>
          <Link to="/page10">Page10</Link>
        </li>
        <li>
          <Link to="/i08r">I08r</Link>
        </li>
        <li>
          <Link to="/page11">Page11</Link>
        </li>
        <li>
          <Link to="/i091">I091</Link>
        </li>
        <li>
          <Link to="/i14">I14</Link>
        </li>
        <li>
          <Link to="/i15">I15</Link>
        </li>
        <li>
          <Link to="/page12">Page12</Link>
        </li>
        <li>
          <Link to="/page13">Page13</Link>
        </li>
        <li>
          <Link to="/one2">One2</Link>
        </li>
        <li>
          <Link to="/page14">Page14</Link>
        </li>
        <li>
          <Link to="/page15">Page15</Link>
        </li>
        <li>
          <Link to="/page16">Page16</Link>
        </li>
        <li>
          <Link to="/page17">Page17</Link>
        </li>
        <li>
          <Link to="/page18">Page18</Link>
        </li>
        <li>
          <Link to="/page19">Page19</Link>
        </li>
        <li>
          <Link to="/page20">Page20</Link>
        </li>
        <li>
          <Link to="/page21">Page21</Link>
        </li>
        <li>
          <Link to="/page22">Page22</Link>
        </li>
        <li>
          <Link to="/page23">Page23</Link>
        </li>
        <li>
          <Link to="/page24">Page24</Link>
        </li>
        <li>
          <Link to="/page25">Page25</Link>
        </li>
        <li>
          <Link to="/page26">Page26</Link>
        </li>
        <li>
          <Link to="/one3">One3</Link>
        </li>
        <li>
          <Link to="/page27">Page27</Link>
        </li>
        <li>
          <Link to="/page28">Page28</Link>
        </li>
        <li>
          <Link to="/page29">Page29</Link>
        </li>
        <li>
          <Link to="/page30">Page30</Link>
        </li>
        <li>
          <Link to="/page31">Page31</Link>
        </li>
        <li>
          <Link to="/page33">Page33</Link>
        </li>
        <li>
          <Link to="/page34">Page34</Link>
        </li>
        <li>
          <Link to="/page35">Page35</Link>
        </li>
        <li>
          <Link to="/page36">Page36</Link>
        </li>
        <li>
          <Link to="/page37">Page37</Link>
        </li>
        <li>
          <Link to="/page38">Page38</Link>
        </li>
        <li>
          <Link to="/page39">Page39</Link>
        </li>
        <li>
          <Link to="/page40">Page40</Link>
        </li>
        <li>
          <Link to="/page41">Page41</Link>
        </li>
        <li>
          <Link to="/page42">Page42</Link>
        </li>
        <li>
          <Link to="/page43">Page43</Link>
        </li>
        <li>
          <Link to="/frame579">Frame579</Link>
        </li>
        <li>
          <Link to="/page44">Page44</Link>
        </li>
        <li>
          <Link to="/one4">One4</Link>
        </li>
        <li>
          <Link to="/page45">Page45</Link>
        </li>
        <li>
          <Link to="/page46">Page46</Link>
        </li>
        <li>
          <Link to="/page47">Page47</Link>
        </li>
        <li>
          <Link to="/page48">Page48</Link>
        </li>
        <li>
          <Link to="/page49">Page49</Link>
        </li>
        <li>
          <Link to="/one5">One5</Link>
        </li>
        <li>
          <Link to="/page50">Page50</Link>
        </li>
        <li>
          <Link to="/page51">Page51</Link>
        </li>
        <li>
          <Link to="/page52">Page52</Link>
        </li>
        <li>
          <Link to="/page53">Page53</Link>
        </li>
        <li>
          <Link to="/page54">Page54</Link>
        </li>
        <li>
          <Link to="/page55">Page55</Link>
        </li>
        <li>
          <Link to="/page56">Page56</Link>
        </li>
        <li>
          <Link to="/page57">Page57</Link>
        </li>
        <li>
          <Link to="/page58">Page58</Link>
        </li>
        <li>
          <Link to="/page59">Page59</Link>
        </li>
        <li>
          <Link to="/page60">Page60</Link>
        </li>
        <li>
          <Link to="/page61">Page61</Link>
        </li>
        <li>
          <Link to="/page62">Page62</Link>
        </li>
        <li>
          <Link to="/page63">Page63</Link>
        </li>
        <li>
          <Link to="/page64">Page64</Link>
        </li>
        <li>
          <Link to="/page65">Page65</Link>
        </li>
        <li>
          <Link to="/page66">Page66</Link>
        </li>
        <li>
          <Link to="/page67">Page67</Link>
        </li>
        <li>
          <Link to="/page68">Page68</Link>
        </li>
        <li>
          <Link to="/page69">Page69</Link>
        </li>
        <li>
          <Link to="/page70">Page70</Link>
        </li>
        <li>
          <Link to="/page71">Page71</Link>
        </li>
        <li>
          <Link to="/page72">Page72</Link>
        </li>
        <li>
          <Link to="/page73">Page73</Link>
        </li>
        <li>
          <Link to="/page74">Page74</Link>
        </li>
        <li>
          <Link to="/page75">Page75</Link>
        </li>
        <li>
          <Link to="/page76">Page76</Link>
        </li>
        <li>
          <Link to="/i012">I012</Link>
        </li>
        <li>
          <Link to="/i022">I022</Link>
        </li>
        <li>
          <Link to="/i032">I032</Link>
        </li>
        <li>
          <Link to="/i04docker">I04docker</Link>
        </li>
        <li>
          <Link to="/i052">I052</Link>
        </li>
        <li>
          <Link to="/i062">I062</Link>
        </li>
        <li>
          <Link to="/i071">I071</Link>
        </li>
        <li>
          <Link to="/i081">I081</Link>
        </li>
        <li>
          <Link to="/i092">I092</Link>
        </li>
        <li>
          <Link to="/i102">I102</Link>
        </li>
        <li>
          <Link to="/i111">I111</Link>
        </li>
        <li>
          <Link to="/i121">I121</Link>
        </li>
        <li>
          <Link to="/i131">I131</Link>
        </li>
        <li>
          <Link to="/i013">I013</Link>
        </li>
        <li>
          <Link to="/i023">I023</Link>
        </li>
        <li>
          <Link to="/i033">I033</Link>
        </li>
        <li>
          <Link to="/page77">Page77</Link>
        </li>
        <li>
          <Link to="/404">404</Link>
        </li>
        <li>
          <Link to="/page78">Page78</Link>
        </li>
        <li>
          <Link to="/page79">Page79</Link>
        </li>
        <li>
          <Link to="/page80">Page80</Link>
        </li>
        <li>
          <Link to="/one6">One6</Link>
        </li>
        <li>
          <Link to="/page81">Page81</Link>
        </li>
        <li>
          <Link to="/page82">Page82</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
